#Tardis Blocks Mod 1.19 TOML

modLoader="javafml" #mandatory
loaderVersion="[41,)" #mandatory
license="MIT"

[[mods]] #mandatory

modId="blockmod" #mandatory
version="0.0.1.0" #mandatory
displayName="Tardis Blocks Mod" #mandatory
logoFile="BlueBox.png" #optional
credits="Mom and KD got me into this." #optional
authors="Dave does not do pretty" #optional

# The description text for the mod (multi line!) (#mandatory)
description='''
This should allow the creation and placement of a smiley block
in Forge 1.19. Additionally, a sad block (exploding) and
a mob slaying block.
'''

[[dependencies.blockmod]] #optional

    modId="forge" #mandatory
    mandatory=true #mandatory
    versionRange="[41,)" #mandatory
    ordering="NONE"
    side="BOTH"

# Here's another dependency
[[dependencies.blockmod]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.19,1.20)"
    ordering="NONE"
    side="BOTH"
